name: Django CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with SQLite
      run: |
        python manage.py test
      env:
        DEBUG: True
        SECRET_KEY: test-secret-key-for-ci
        USE_POSTGRES: False

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety bandit

    - name: Check for security vulnerabilities
      run: |
        safety check

    - name: Run bandit security linter
      run: |
        bandit -r attendance/